import { register } from 'registyle/collector';

register.all({
  'app-shell': {
    tw: 'flex min-h-screen',
    'background-color': 'var(--c-bg)',
    '@media (max-width: 760px)': { 'flex-direction': 'column' },
  },
  'sidebar': {
    tw: 'flex flex-col flex-shrink-0 overflow-y-auto',
    width: '252px',
    'background-color': 'var(--c-sidebar)',
    'border-right': '1px solid var(--c-sidebar-border)',
    padding: '1.25rem 0 1rem',
    position: 'sticky',
    top: '0',
    height: '100vh',
    'scrollbar-width': 'thin',
    'scrollbar-color': '#52645a transparent',
    '@media (max-width: 760px)': {
      position: 'sticky',
      width: '100%',
      height: 'auto',
      padding: '0.75rem 1rem 0',
      'border-right': '0',
      'border-bottom': '1px solid var(--c-sidebar-border)',
      'overflow-y': 'hidden',
      'z-index': '20',
    },
  },
  'sidebar-logo': {
    tw: 'flex items-center gap-2.5 font-bold mb-6',
    'font-size': '16px',
    padding: '0 1.25rem',
    color: '#f5f7f4',
    'font-family': "'Fraunces', Georgia, serif",
    '@media (max-width: 760px)': { 'margin-bottom': '0.65rem', padding: '0 0.25rem' },
  },
  'brand-mark': {
    tw: 'inline-flex items-center justify-center rounded',
    width: '23px',
    height: '23px',
    color: '#fff',
    'background-color': 'var(--c-brand)',
    'font-family': "'DM Sans', sans-serif",
    'font-size': '13px',
  },
  'sidebar-nav': {
    tw: 'flex',
    'flex-direction': 'column',
    gap: '0.25rem',
    '@media (max-width: 760px)': {
      'flex-direction': 'row',
      'overflow-x': 'auto',
      'scrollbar-width': 'none',
      gap: '0.5rem',
      'padding-bottom': '0.5rem',
    },
  },
  'sidebar-group': {
    tw: 'flex',
    'flex-direction': 'column',
    '@media (max-width: 760px)': { 'flex-direction': 'row', 'flex-shrink': '0' },
  },
  'sidebar-group-label': {
    tw: 'px-5 font-bold tracking-widest uppercase mb-1 mt-4',
    display: 'block',
    'font-size': '9px',
    color: 'var(--c-sidebar-muted)',
    '@media (max-width: 760px)': { display: 'none' },
  },
  'sidebar-item': {
    tw: 'flex items-center gap-2.5 text-sm font-medium transition-colors cursor-pointer border-0 bg-transparent text-left',
    width: '100%',
    padding: '0.5rem 1.25rem',
    color: 'var(--c-sidebar-muted)',
    'border-radius': '0',
    'border-left': '2px solid transparent',
    '&:hover': { color: '#fff', 'background-color': 'rgba(255,255,255,.055)' },
    '&:focus-visible': { outline: '2px solid var(--c-brand)', 'outline-offset': '-2px' },
    '@media (max-width: 760px)': {
      width: 'auto',
      'flex-shrink': '0',
      padding: '0.55rem 0.7rem',
      'border-left': '0',
      'border-bottom': '2px solid transparent',
      'border-radius': '5px 5px 0 0',
      'font-size': '12px',
    },
  },
  'sidebar-item-active': {
    tw: 'flex items-center gap-2.5 text-sm font-semibold cursor-pointer border-0 text-left',
    width: '100%',
    padding: '0.5rem 1.25rem',
    color: '#fff',
    'background-color': '#31473e',
    'border-left': '2px solid var(--c-brand)',
    '&:focus-visible': { outline: '2px solid var(--c-brand)', 'outline-offset': '-2px' },
    '@media (max-width: 760px)': {
      width: 'auto',
      'flex-shrink': '0',
      padding: '0.55rem 0.7rem',
      'border-left': '0',
      'border-bottom': '2px solid var(--c-brand)',
      'border-radius': '5px 5px 0 0',
      'font-size': '12px',
    },
  },
  'main-content': {
    tw: 'flex-1 min-w-0 overflow-y-auto',
    padding: '2.25rem clamp(1.5rem, 4vw, 4.5rem)',
    '@media (max-width: 760px)': { padding: '1.5rem 1.25rem' },
    '@media (max-width: 480px)': { padding: '1.1rem 1rem' },
  },
  'content-frame': { width: '100%', 'max-width': '1280px', margin: '0 auto' },
  'demo-topline': {
    tw: 'flex items-center justify-between',
    'margin-bottom': '1.5rem',
    'min-height': '24px',
    '@media (max-width: 480px)': { 'margin-bottom': '1rem' },
  },
  'demo-location': {
    tw: 'font-bold uppercase',
    'font-size': '10px',
    'letter-spacing': '0.12em',
    color: 'var(--c-text-muted)',
  },
  'demo-count': {
    tw: 'inline-flex items-center rounded-full px-2.5 py-1 font-semibold',
    'font-size': '11px',
    color: 'var(--c-info)',
    'background-color': 'var(--c-info-bg)',
  },
  'demo-header': {
    tw: 'flex justify-between gap-6',
    'align-items': 'flex-end',
    'margin-bottom': '2rem',
    'border-bottom': '1px solid var(--c-border)',
    'padding-bottom': '1.5rem',
    animation: 'fadeIn 240ms ease both',
    '@media (max-width: 560px)': { 'align-items': 'flex-start', 'margin-bottom': '1.5rem', 'padding-bottom': '1rem' },
  },
  'demo-heading-copy': { 'max-width': '760px' },
  'demo-eyebrow': {
    tw: 'block font-bold uppercase mb-2',
    'font-size': '10px',
    'letter-spacing': '0.14em',
    color: 'var(--c-brand)',
  },
  'demo-title': {
    tw: 'font-medium mb-1',
    'font-family': "'Fraunces', Georgia, serif",
    'font-size': '3.25rem',
    'line-height': '1.08',
    color: 'var(--c-text)',
    '@media (max-width: 560px)': { 'font-size': '2.5rem' },
  },
  'demo-desc': {
    'font-size': '15px',
    color: 'var(--c-text-muted)',
    'line-height': '1.6',
    '@media (max-width: 560px)': { 'font-size': '14px' },
  },
  'demo-index': {
    tw: 'flex items-baseline gap-1 font-semibold',
    'flex-shrink': '0',
    'font-family': "'Fraunces', Georgia, serif",
    'font-size': '30px',
    color: 'var(--c-brand)',
    '& span': { 'font-family': "'DM Sans', sans-serif", 'font-size': '12px', color: 'var(--c-text-light)' },
    '@media (max-width: 560px)': { display: 'none' },
  },
  'demo-stage': { 'min-height': '360px', 'padding-bottom': '2rem' },
  'demo-section': {
    tw: 'mb-9',
    'padding-bottom': '1.65rem',
    'border-bottom': '1px solid var(--c-border)',
    '&:last-child': { 'border-bottom': '0', 'padding-bottom': '0' },
  },
  'demo-section-title': {
    tw: 'font-semibold mb-4',
    'font-size': '12px',
    color: 'var(--c-text-muted)',
  },
  'demo-row':  { tw: 'flex flex-wrap items-center gap-3' },
  'demo-col':  { tw: 'flex flex-col gap-3' },
  'demo-grid': { tw: 'grid gap-4', 'grid-template-columns': 'repeat(auto-fit, minmax(min(100%, 250px), 1fr))' },
  'code-badge': {
    tw: 'inline-flex items-center px-2 py-0.5 rounded font-mono',
    'font-size': '12px',
    'background-color': 'var(--c-brand-light)',
    color: 'var(--c-brand)',
  },
});
