import { register } from 'registyle/collector';

register.all({
  'app-shell': { tw: 'flex min-h-screen bg-[var(--c-bg)] max-[760px]:flex-col' },
  sidebar: { tw: 'flex w-[252px] flex-col shrink-0 overflow-y-auto sticky top-0 h-screen bg-[var(--c-sidebar)] border-r border-[var(--c-sidebar-border)] px-0 pt-5 pb-4 [scrollbar-width:thin] [scrollbar-color:#52645a_transparent] max-[760px]:sticky max-[760px]:w-full max-[760px]:h-auto max-[760px]:px-4 max-[760px]:pt-3 max-[760px]:pb-0 max-[760px]:border-r-0 max-[760px]:border-b max-[760px]:z-20' },
  'sidebar-logo': { tw: 'flex items-center gap-2.5 font-bold mb-6 [font-size:16px] px-5 text-[#f5f7f4] [font-family:Fraunces,Georgia,serif] max-[760px]:px-1' },
  'brand-mark': { tw: 'inline-flex size-[23px] items-center justify-center rounded text-white bg-[var(--c-brand)] [font-family:DM_Sans,sans-serif] text-[13px]' },
  'sidebar-nav': { tw: 'flex flex-col gap-1 max-[760px]:flex-row max-[760px]:overflow-x-auto max-[760px]:[scrollbar-width:none] max-[760px]:gap-2 max-[760px]:pb-2' },
  'sidebar-group': { tw: 'flex flex-col max-[760px]:flex-row max-[760px]:shrink-0' },
  'sidebar-group-label': { tw: 'block px-5 font-bold tracking-widest uppercase mb-1 mt-4 text-[9px] text-[var(--c-sidebar-muted)] max-[760px]:hidden' },
  'sidebar-item': { tw: 'flex w-full items-center gap-2.5 text-sm font-medium transition-colors cursor-pointer border-0 bg-transparent text-left px-5 py-2 text-[var(--c-sidebar-muted)] rounded-none hover:text-white hover:bg-[rgba(255,255,255,.055)] focus-visible:outline-2 focus-visible:outline-[var(--c-brand)] focus-visible:outline-offset-[-2px] max-[760px]:w-auto max-[760px]:shrink-0 max-[760px]:px-[.7rem] max-[760px]:py-[.55rem] max-[760px]:border-l-0 max-[760px]:rounded-t-[5px]' },
  'sidebar-item-active': { tw: 'flex w-full items-center gap-2.5 text-sm font-semibold cursor-pointer border-0 text-left px-5 py-2 text-white bg-[#31473e] border-l-[var(--c-brand)] focus-visible:outline-2 focus-visible:outline-[var(--c-brand)] focus-visible:outline-offset-[-2px] max-[760px]:w-auto max-[760px]:shrink-0 max-[760px]:px-[.7rem] max-[760px]:py-[.55rem] max-[760px]:border-l-0 max-[760px]:border-b-[var(--c-brand)] max-[760px]:rounded-t-[5px]' },
  'main-content': { tw: 'flex-1 min-w-0 overflow-y-auto px-[clamp(1.5rem,4vw,4.5rem)] py-9 max-[760px]:px-5 max-[760px]:py-6 max-[480px]:px-4 max-[480px]:py-[1.1rem]' },
  'content-frame': { tw: 'w-full max-w-[1280px] mx-auto' },
  'demo-topline': { tw: 'flex min-h-6 items-center justify-between mb-6 max-[480px]:mb-4' },
  'demo-location': { tw: 'font-bold uppercase text-[10px] tracking-[.12em] text-[var(--c-text-muted)]' },
  'demo-count': { tw: 'inline-flex items-center rounded-full px-2.5 py-1 font-semibold text-[11px] text-[var(--c-info)] bg-[var(--c-info-bg)]' },
  'demo-header': { tw: 'flex justify-between items-end gap-6 mb-8 border-b border-[var(--c-border)] pb-6 animate-[fadeIn_240ms_ease_both] max-[560px]:items-start max-[560px]:mb-6 max-[560px]:pb-4' },
  'demo-heading-copy': { tw: 'max-w-[760px]' },
  'demo-eyebrow': { tw: 'block font-bold uppercase mb-2 text-[10px] tracking-[.14em] text-[var(--c-brand)]' },
  'demo-title': { tw: 'font-medium mb-1 [font-family:Fraunces,Georgia,serif] text-[3.25rem] leading-[1.08] text-[var(--c-text)] max-[560px]:text-[2.5rem]' },
  'demo-desc': { tw: 'text-[15px] text-[var(--c-text-muted)] leading-[1.6] max-[560px]:text-sm' },
  'demo-index': { tw: 'flex shrink-0 items-baseline gap-1 font-semibold [font-family:Fraunces,Georgia,serif] text-[30px] text-[var(--c-brand)] [&>span]:[font-family:DM_Sans,sans-serif] [&>span]:[font-size:12px] [&>span]:text-[var(--c-text-light)]' },
  'demo-stage': { tw: 'min-h-[360px] pb-8' },
  'demo-section': { tw: 'mb-9 pb-[1.65rem] border-b border-[var(--c-border)] last:[border-bottom:0] last:pb-0' },
  'demo-section-title': { tw: 'font-semibold mb-4 [font-size:12px] text-[var(--c-text-muted)]' },
  'demo-row': { tw: 'flex flex-wrap items-center gap-3' },
  'demo-col': { tw: 'flex flex-col gap-3' },
  'demo-grid': { tw: 'grid gap-4 [grid-template-columns:repeat(auto-fit,minmax(min(100%,250px),1fr))]' },
  'code-badge': { tw: 'inline-flex items-center px-2 py-0.5 rounded font-mono [font-size:12px] bg-[var(--c-brand-light)] text-[var(--c-brand)]' },
});
