import { register } from 'registyle/collector';

register('mui-typography', {
  base: { tw: 'm-0 text-[var(--mui-typography-color,var(--text,#edf2fb))]' },
  modifiers: {
    h1: { tw: 'text-4xl leading-tight tracking-tight' },
    h2: { tw: 'text-3xl leading-tight tracking-tight' },
    h3: { tw: 'text-2xl leading-snug' },
    h4: { tw: 'text-xl leading-snug' },
    subtitle1: { tw: 'text-base leading-6' },
    subtitle2: { tw: 'text-sm leading-5' },
    body1: { tw: 'text-sm leading-6' },
    body2: { tw: 'text-xs leading-5' },
    caption: { tw: 'text-xs leading-4' },
    overline: { tw: 'text-[10px] uppercase tracking-[.08em]' },
    inherit: { tw: 'text-inherit' },
    left: { tw: 'text-left' },
    center: { tw: 'text-center' },
    right: { tw: 'text-right' },
    justify: { tw: 'text-justify' },
    'weight-regular': { tw: 'font-normal' },
    'weight-medium': { tw: 'font-medium' },
    'weight-bold': { tw: 'font-bold' },
    'color-primary': { tw: '[--mui-typography-color:var(--mui-blue,#9bbcff)]' },
    'color-secondary': { tw: '[--mui-typography-color:var(--muted,#9aa8bd)]' },
    'color-success': { tw: '[--mui-typography-color:#69b890]' },
    'color-warning': { tw: '[--mui-typography-color:#e9ad64]' },
    'color-danger': { tw: '[--mui-typography-color:#e47b84]' },
  },
});
